### ISSUE TITLE
增加支持阿里云 HSF

### ISSUE THREAD

**Issue by songlonqi-java** [GuanceCloud/dd-trace-java#14]
[阿里云 hsf 介绍](https://help.aliyun.com/document_detail/100087.html)

**Comment by pugpngying123** [comment]
edas 版本：
![image](https://user-images.githubusercontent.com/10216931/207762580-6380a941-aee5-47df-b1db-090d7a941cff.png)
hsf本身的jar包：
因为jar包太大，100M，无法上传，需要的话，可以找冯海杰要

**Comment by lrwh** [comment]
已支持，hsf版本为：2.2.8.2--2019-06-stable
