### ISSUE TITLE
support get redis command parameter

### ISSUE THREAD

**Issue by Harlonxl** [GuanceCloud/dd-trace-java#19]
for example: GET somekey
trace detail should be contain parameter: somekey

**Comment by songlonqi-java** [comment]
排查redis相关问题时，只能获取到具体执行的命令，不能获取到参数key，是否可以支持获取redis请求参数？

![4K89Muv9zuU](https://user-images.githubusercontent.com/31207055/211498499-fc82c938-abab-465d-91b2-e94b245d28e4.png)

**Comment by songlonqi-java** [comment]
那就 添加一个环境变量  redis.command.raw=true  用来开关

**Comment by songlonqi-java** [comment]
环境变量  -Ddd.redis.command.args=true
