### ISSUE TITLE
支持 RocketMQ 4.0 的版本

### ISSUE THREAD

**Issue by imjiachuan** [GuanceCloud/dd-trace-java#20]
目前最新的1.3.0的版本针对阿里云的 RocketMQ 云产品支持的版本要求是4.8及以上的。
这边有客户是 阿里云RocketMQ 4.0系列标准版。
需要进行适配支持，麻烦支持下。

**Comment by songlonqi-java** [comment]
我看了下阿里云RocketMQ文档，阿里云提供的代码示例： https://github.com/AliwareMQ/mq-demo

这是一个不同与之前的两种源码 `org.apache.rocketmq.client` 和 `org.apache.rocketmq.client.java`   而是另外一个jar包：`com.aliyun.openservices.ons-client`

**Comment by songlonqi-java** [comment]
目前支持 ons-client 1.8 以上版本
