### ISSUE TITLE
支持MongoDB

### ISSUE THREAD

**Issue by imjiachuan** [GuanceCloud/dd-trace-java#38]
观测云二开的dd-trace-java包，需要能支持MongoDB链路的监控。还需要能支持MongoDB数据的不脱敏配置，就是可以看到原始sql。

**Comment by songlonqi-java** [comment]
脱敏目前实现的有： int32 int64 Double Timestamp， bool ，string 。 没有实现的有 BinaryDate(session id),  DBPointer, js,MinKey,MaxKey 等没有实际意义的值

**Comment by songlonqi-java** [comment]
使用启动参数 `-Ddd.mongo.obfuscation=true` 或者环境变量 `DD_MONGO_OBFUSCATION=true` 开启脱敏。这样从观测云上就可以看见一条具体的命令。
