### ISSUE TITLE
RocketMQ支持的问题

### ISSUE THREAD

**Issue by zhaogangxp** [GuanceCloud/dd-trace-java#43]
1.14.0-guance分支中，对RocketMQ的链路处理有一个bug，RocketMQ发送异步消息的时候是不返回sendResult的，但是在这个分支中RocketMQDecorator end函数没有做过滤判定，会出现npe异常。1.15.4-guance中也存在这个问题。

**Comment by songlonqi-java** [comment]
v1.17.1-guance 版本已经修复该bug
