### ISSUE TITLE
rabbitMQ在链路中的串联支持

### ISSUE THREAD

**Issue by HarryTu** [GuanceCloud/dd-trace-java#51]
Java agent 支持  rabbitMQ（版本：3.7.6）在链路中的串联，例如：能够完全显示 服务A -> rabbitMQ -> 服务B。

**Comment by songlonqi-java** [comment]
本地测试了一下，确实是链接不上的。traceid 不一致，下周重点处理一下这个问题

**Comment by songlonqi-java** [comment]
![image](https://github.com/GuanceCloud/dd-trace-java/assets/31207055/8cc9f032-cd00-4507-970c-474ce245a186)

**Comment by songlonqi-java** [comment]
![image](https://github.com/GuanceCloud/dd-trace-java/assets/31207055/2dcef60b-a2d1-48dc-8b25-b0ec2aeacadb)

该图为 服务A 在收到请求 /rabbit 之后，生产一条消息，最后 另一个服务消费消息的调用图。
