### ISSUE TITLE
AArch64平台下安装不成功的问题

### ISSUE THREAD

**Issue by kyriertan** [GuanceCloud/dd-trace-java#62]
进入项目目录，使用 sudo ./gradlew build构建包，出现如下错误：
[tanr@localhost dd-trace-java-master]$ sudo ./gradlew build

> Configure project :
Failed to open repository, trying to work without it org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/tanr/dev_space/dd_trace_java/guancecloud/dd-trace-java-master
Couldn't perform is legacy DefTagname Repository command on uninitialized repository
Could not resolve current position on uninitialized repository, returning default
Could not resolve current position on uninitialized repository, returning default
Couldn't perform check uncommitted changes command on uninitialized repository

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/home/tanr/dev_space/dd_trace_java/guancecloud/dd-trace-java-master/gradle/java_no_deps.gradle' line: 289

* What went wrong:
A problem occurred evaluating project ':dd-smoke-tests:agent-bootstrap'.
> No matching toolchains found for requested specification: {languageVersion=17, vendor=any, implementation=vendor-specific} for LINUX on aarch64.
   > No locally installed toolchains match and toolchain auto-provisioning is not enabled.

* Try:
> Learn more about toolchain auto-detection at https://docs.gradle.org/8.3/userguide/toolchains.html#sec:auto_detection.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script '/home/tanr/dev_space/dd_trace_java/guancecloud/dd-trace-java-master/gradle/java_no_deps.gradle' line: 289

* What went wrong:
A problem occurred configuring project ':dd-smoke-tests:agent-bootstrap'.
> Could not create task ':dd-smoke-tests:agent-bootstrap:forkedTest'.
   > No matching toolchains found for requested specification: {languageVersion=17, vendor=any, implementation=vendor-specific} for LINUX on aarch64.
      > No locally installed toolchains match and toolchain auto-provisioning is not enabled.

* Try:
> Learn more about toolchain auto-detection at https://docs.gradle.org/8.3/userguide/toolchains.html#sec:auto_detection.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
==============================================================================

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1m 50s
14 actionable tasks: 10 executed, 4 from cache

**Comment by lrwh** [comment]
主要问题是环境没有配置好，参考 [ddtrace 系列篇之 dd-trace-java 项目编译](https://juejin.cn/post/7273024681631383613)
